import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { VitePWA } from 'vite-plugin-pwa'

// import { analyzer } from 'vite-bundle-analyzer'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['icon.svg'],
      manifest: {
        name: 'Daily Utils',
        short_name: 'Utils',
        description: 'Offline-first utils app',
        theme_color: '#ffffff',
        icons: [
          {
            src: 'icon.svg',
            type: 'image/svg'
          }
        ]
      },
      workbox: {
        // Caches all internal assets generated by the build
        globPatterns: ['**/*.{js,css,html,ico,png,svg}'],
        // Ensure app works even if the user is completely offline
        runtimeCaching: [
          {
            urlPattern: ({ request }) => request.destination === 'document',
            handler: 'NetworkFirst', // Check network, fallback to cache
          }
        ]
      }
    }),
    // analyzer(),
  ],
  base: "/daily-utils",
});
